In [1]:
import pandas as pd
from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img

Using TensorFlow backend.


In [2]:
datagen = ImageDataGenerator(
        # a value in degrees (0-180), a range within which to randomly rotate pictures
        rotation_range=40,
        # ranges (as a fraction of total width or height) within which to randomly translate pictures vertically or horizontally
        width_shift_range=0.2,
        height_shift_range=0.2,
        # a value by which we will multiply the data before any other processing.
        # Our original images consist in RGB coefficients in the 0-255, 
        # but such values would be too high for our models to process (given a typical learning rate),
        # so we target values between 0 and 1 instead by scaling with a 1/255. factor.
        rescale=1./255,
        # for randomly applying shearing transformations
        shear_range=0.2,
        # for randomly zooming inside pictures
        zoom_range=0.2,
        # for randomly flipping half of the images horizontally --relevant when there are no assumptions of horizontal assymetry (e.g. real-world pictures).
        horizontal_flip=True,
        # the strategy used for filling in newly created pixels, which can appear after a rotation or a width/height shift.
        fill_mode='nearest')

In [3]:
img = load_img('train/cat.0.jpg')  # this is a PIL image
x = img_to_array(img)  # this is a Numpy array with shape (3, 150, 150)
x = x.reshape((1,) + x.shape)  # this is a Numpy array with shape (1, 3, 150, 150)

In [22]:
# the .flow() command below generates batches of randomly transformed images
# and saves the results to the `preview/` directory
i = 0
for batch in datagen.flow(x, batch_size=16,
                          save_to_dir='preview', save_prefix='cat', save_format='jpeg'):
    i += 1
    print("batch: {}".format(batch))
    if i > 20:
        break  # otherwise the generator would loop indefinitely

batch: [[[[ 0.81176478  0.63921571  0.35294119]
   [ 0.81176478  0.63921571  0.35294119]
   [ 0.81176478  0.63921571  0.35294119]
   ..., 
   [ 0.98715675  0.88519597  0.59107828]
   [ 0.99215692  0.89019614  0.59607846]
   [ 0.99215692  0.89019614  0.59607846]]

  [[ 0.81176478  0.63921571  0.35294119]
   [ 0.81176478  0.63921571  0.35294119]
   [ 0.81176478  0.63921571  0.35294119]
   ..., 
   [ 0.98830134  0.88634056  0.59222293]
   [ 0.99215692  0.89019614  0.59607846]
   [ 0.99215692  0.89019614  0.59607846]]

  [[ 0.81176478  0.63921571  0.35294119]
   [ 0.81176478  0.63921571  0.35294119]
   [ 0.81176478  0.63921571  0.35294119]
   ..., 
   [ 0.98944598  0.88748521  0.59336758]
   [ 0.99215692  0.89019614  0.59607846]
   [ 0.99215692  0.89019614  0.59607846]]

  ..., 
  [[ 0.59215689  0.47058827  0.20784315]
   [ 0.59215689  0.47058827  0.20784315]
   [ 0.59215689  0.47058827  0.20784315]
   ..., 
   [ 0.00784314  0.00784314  0.        ]
   [ 0.00784314  0.00784314  0.        ]


batch: [[[[ 0.97550476  0.80687726  0.49707329]
   [ 0.97647065  0.80784321  0.49803925]
   [ 0.97647065  0.80784321  0.49803925]
   ..., 
   [ 0.98039222  0.86720419  0.59108198]
   [ 0.98039222  0.86887056  0.58774924]
   [ 0.98039222  0.87053686  0.58441657]]

  [[ 0.97414452  0.80551708  0.49571314]
   [ 0.97647065  0.80784321  0.49803925]
   [ 0.97647065  0.80784321  0.49803925]
   ..., 
   [ 0.98039222  0.87010664  0.58527702]
   [ 0.98039222  0.8705883   0.58431375]
   [ 0.98039222  0.8705883   0.58431375]]

  [[ 0.97278434  0.8041569   0.494353  ]
   [ 0.97632396  0.80769652  0.49789262]
   [ 0.97647065  0.80784321  0.49803925]
   ..., 
   [ 0.98039222  0.8705883   0.58431375]
   [ 0.98039222  0.8705883   0.58431375]
   [ 0.98039222  0.8705883   0.58431375]]

  ..., 
  [[ 0.78039223  0.627451    0.32549021]
   [ 0.78039223  0.627451    0.32549021]
   [ 0.78039223  0.627451    0.32549021]
   ..., 
   [ 0.53817862  0.38843444  0.14204393]
   [ 0.52917027  0.37750238  0.13669284]


batch: [[[[ 0.99215692  0.90196085  0.58823532]
   [ 0.99215692  0.90196085  0.58823532]
   [ 0.99215692  0.90196085  0.58823532]
   ..., 
   [ 0.7843138   0.63137257  0.32156864]
   [ 0.7843138   0.63137257  0.32156864]
   [ 0.7843138   0.63137257  0.32156864]]

  [[ 0.99215692  0.90196085  0.58823532]
   [ 0.99215692  0.90196085  0.58823532]
   [ 0.99215692  0.90196085  0.58823532]
   ..., 
   [ 0.7843138   0.63137257  0.32156864]
   [ 0.7843138   0.63137257  0.32156864]
   [ 0.7843138   0.63137257  0.32156864]]

  [[ 0.99215692  0.90196085  0.58823532]
   [ 0.99215692  0.90196085  0.58823532]
   [ 0.99215692  0.90196085  0.58823532]
   ..., 
   [ 0.7843138   0.63137257  0.32156864]
   [ 0.7843138   0.63137257  0.32156864]
   [ 0.7843138   0.63137257  0.32156864]]

  ..., 
  [[ 0.09803922  0.09803922  0.        ]
   [ 0.09803922  0.09803922  0.        ]
   [ 0.10011945  0.09803922  0.00416046]
   ..., 
   [ 0.2392157   0.15294118  0.00784314]
   [ 0.2392157   0.15294118  0.00784314]


batch: [[[[ 0.72063434  0.44923678  0.21786423]
   [ 0.70436382  0.43025446  0.19888189]
   [ 0.68347073  0.40433836  0.17527707]
   ..., 
   [ 0.98085791  0.85928929  0.53865212]
   [ 0.98039222  0.85433149  0.53500891]
   [ 0.98350096  0.85201669  0.53333336]]

  [[ 0.73153317  0.46353474  0.23129892]
   [ 0.71439934  0.4419626   0.21059005]
   [ 0.69685143  0.42106426  0.19033037]
   ..., 
   [ 0.98253053  0.86096191  0.54366982]
   [ 0.98039222  0.85767668  0.53668147]
   [ 0.98039222  0.85225314  0.53396976]]

  [[ 0.74324131  0.48026067  0.24635223]
   [ 0.72443485  0.45367071  0.22229818]
   [ 0.70816433  0.43468839  0.20331585]
   ..., 
   [ 0.9842031   0.86263442  0.54868758]
   [ 0.98149133  0.85992271  0.54055232]
   [ 0.98039222  0.85559833  0.53564227]]

  ..., 
  [[ 0.78039223  0.627451    0.31914482]
   [ 0.78039223  0.627451    0.31764707]
   [ 0.78039223  0.627451    0.31764707]
   ..., 
   [ 0.30473828  0.20367692  0.0311279 ]
   [ 0.3019608   0.20784315  0.03529412]
